# Generated by Django 4.2 on 2023-04-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('101', '101 Films'), ('20t', '20th Century Fox'), ('88F', '88 Films'), ('Arr', 'Arrow'), ('BFI', 'BFI Video'), ('Bey', 'Beyond Home Entertainment'), ('Blu', 'Blue Underground'), ('Cod', 'Code Red'), ('Cri', 'Criterion'), ('Dar', 'Dark Force Entertainment'), ('Duk', 'Duke Marketing'), ('Ent', 'Entertainment One'), ('Eur', 'Eureka Entertainment'), ('Fil', 'Film Chest'), ('Fox', 'Fox/MGM'), ('Gla', 'Glass Doll Films'), ('Gri', 'Grindhouse Releasing'), ('Gry', 'Gryphon Entertainment'), ('Ico', 'Icon Film Distribution'), ('Imp', 'Imprint'), ('Kin', 'Kino Lorber'), ('MPI', 'MPI Media Group'), ('Mad', 'Madman Entertainment'), ('Met', 'Metro-Goldwyn-Mayer'), ('Mil', 'Mill Creek Entertainment'), ('Mod', 'Mondo Macabro'), ('Mon', 'Monster Pictures'), ('Net', 'Network'), ('Oli', 'Olive Films'), ('Par', 'Paramount Pictures'), ('Pow', 'Powerhouse Films'), ('RLJ', 'RLJ Entertainment'), ('Rar', 'RaroVideo U.S.'), ('Red', 'Redemption'), ('Ree', 'Reel'), ('Ret', 'Retromedia'), ('Roa', 'Roadshow Entertainment'), ('Ron', 'Ronin Flix'), ('SRS', 'SRS Cinema'), ('Sat', "Saturn's Core Audio & Video"), ('Sco', 'Scorpion Releasing'), ('Scr', 'Screenbound Pictures'), ('Sec', 'Second Sight'), ('Sev', 'Severin Films'), ('Shc', 'Shock'), ('Sho', 'Shout Factory'), ('Shr', 'Shriek Show'), ('Sir', 'Siren Visual Entertainment'), ('Son', 'Sony Pictures'), ('Sta', 'Starz / Anchor Bay'), ('Stu', 'Studio Canal'), ('Syn', 'Synapse Films'), ('Tem', 'Tempe Digital'), ('Ter', 'Terror Vision'), ('The', 'The Film Detective'), ('Tro', 'Troma'), ('Umb', 'Umbrella Entertainment'), ('Uni', 'Universal Studios'), ('VCI', 'VCI'), ('Via', 'Via Vision Entertainment'), ('Vin', 'Vinegar Syndrome'), ('Vis', 'Visual Entertainment Group'), ('War', 'Warner Bros.'), ('Wic', 'Wicked-Vision Media')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('medium', models.CharField(choices=[('D', 'DVD'), ('B', 'Blu-ray'), ('4', '4K Blu-ray')], default='B', max_length=1)),
                ('standard_size', models.BooleanField(default=True)),
                ('use_collection_name_as_prefix', models.BooleanField(default=False)),
                ('_distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.distributor')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('release_date', models.DateField()),
                ('watched', models.BooleanField(default=False)),
                ('director', models.ManyToManyField(to='movies.director')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.distributor'),
        ),
    ]
