# Generated by Django 4.2 on 2023-04-29 09:07

from django.db import migrations

def forwards_func(apps, schema_editor):
    """Populates the Distributor table with all choices in the Studio TextChoices enum.
    """
    Distributor = apps.get_model("movies", "Distributor")
    db_alias = schema_editor.connection.alias
    Distributor.objects.using(db_alias).bulk_create(
        [
            Distributor(name=studio_code) for studio_code, studio_name in Distributor._meta.get_field('name').choices
        ]
    )


def reverse_func(apps, schema_editor):
    Distributor = apps.get_model("movies", "Distributor")
    db_alias = schema_editor.connection.alias
    Distributor.objects.using(db_alias).filter(name__in=[studio_code for studio_code, studio_name in Distributor._meta.get_field('name').choices])



class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_collection_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
