# Generated by Django 4.2 on 2023-05-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_physicalmedia__distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upc',
            field=models.IntegerField(null=True),
        ),
    ]
