# Generated by Django 4.2 on 2023-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_upc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_in_order',
        ),
        migrations.AddField(
            model_name='movie',
            name='ean',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_prefix',
            field=models.TextField(default=''),
        ),
    ]
