# Generated by Django 4.2 on 2023-05-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_options_remove_movie_title_in_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='year',
        ),
    ]
