# Generated by Django 4.2 on 2023-05-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_multimovieset_movie_multi_movie_sets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multimovieset',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='multimovieset',
            table='multi_movie_set',
        ),
    ]
