# Generated by Django 4.2 on 2023-05-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_multimovieset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='multi_movie_sets',
        ),
        migrations.AddField(
            model_name='multimovieset',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movies.movie'),
        ),
    ]
