# Generated by Django 4.2 on 2023-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_multi_movie_sets_multimovieset_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='prefix',
            field=models.CharField(choices=[('The', 'The'), ('A', 'A'), ('An', 'An')], max_length=3, null=True),
        ),
    ]
